FROM ubuntu:latest
MAINTAINER abhithegreat "abhisheks9988@protonmail.com"

RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD [".py"]


